# Generated by Django 3.2.5 on 2022-04-03 22:36

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('languages', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='language',
            name='language_detail',
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='language',
            name='language_fields',
            field=models.ManyToManyField(related_name='_languages_language_language_fields_+', to='languages.Language'),
        ),
    ]
