# Generated by Django 3.2.5 on 2022-04-03 22:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('languages', '0003_auto_20220404_0246'),
    ]

    operations = [
        migrations.AlterField(
            model_name='language',
            name='language_fields',
            field=models.TextField(blank=True, null=True),
        ),
    ]
