# Generated by Django 3.2.5 on 2022-04-11 22:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userprofile', '0002_alter_detail_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='detail',
            name='about',
            field=models.TextField(),
        ),
    ]
