# Generated by Django 3.2.5 on 2022-04-12 20:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userprofile', '0003_alter_detail_about'),
    ]

    operations = [
        migrations.AddField(
            model_name='detail',
            name='profile_image',
            field=models.ImageField(null=True, upload_to='images/'),
        ),
    ]
