# Generated by Django 3.2.5 on 2022-04-18 18:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('userprofile', '0004_detail_profile_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='detail',
            name='profile_image',
        ),
    ]
