# Generated by Django 3.2.5 on 2022-03-21 01:02

import ckeditor.fields
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Code',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', ckeditor.fields.RichTextField()),
                ('title', models.TextField(max_length=30)),
                ('code_content', models.TextField()),
                ('code_language', models.CharField(choices=[('Java', 'Java'), ('Python', 'Python'), ('C#', 'C#'), ('C++', 'C++'), ('C', 'C'), ('JavaScript', 'JavaScript'), ('Html/Css', 'Html/Css')], max_length=10)),
                ('code_created_date', models.DateTimeField(auto_now_add=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
