# Generated by Django 3.2.5 on 2022-03-30 21:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('code', '0004_auto_20220330_2227'),
    ]

    operations = [
        migrations.AlterField(
            model_name='code',
            name='code_language',
            field=models.CharField(choices=[('Java', 'Java'), ('Python', 'Python'), ('C#', 'C#'), ('C++', 'C++'), ('C', 'C'), ('JavaScript', 'JavaScript'), ('HtmlCss', 'HtmlCss')], max_length=10),
        ),
    ]
