# Generated by Django 3.2.5 on 2022-04-03 22:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('code', '0005_alter_code_code_language'),
    ]

    operations = [
        migrations.AlterField(
            model_name='code',
            name='title',
            field=models.CharField(max_length=20),
        ),
    ]
