# Generated by Django 3.2.5 on 2022-04-07 23:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('code', '0007_comment'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Comment',
        ),
    ]
