# Generated by Django 3.2.5 on 2022-04-18 18:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('code', '0011_alter_code_author'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='code',
            options={'ordering': ['-code_created_date']},
        ),
        migrations.AlterModelOptions(
            name='comment',
            options={'ordering': ['-comment_date']},
        ),
    ]
